#!/usr/bin/env bash

# Use this script to test EnvManager on Linux systems from the command line.
# Use "./envm <options> <command> <args>" to test.
# Use "./gradlew installDist" to generate the bin files.

./build/install/EnvManager/bin/EnvManager "$@"